name: UltrasonicCore
main: me.mig.ultrasoniccore.UltrasonicCore
version: 1.0
Author: Migins
description: A friendly plugin for a friendly server ;)
api-version: 1.16

commands:
  suicide:
    aliases: s
    usage: /suicide
  teleport:
    aliases: tp
    usage: /teleport (<player> [another player]|coordinates)
  reload:
    usage: /reload
    